// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDoCJ15Rw7B4rV47oOPTJV_ipmCQz9r7o',
    appId: '1:773797736663:web:8fe8cfe32ca62db65f8092',
    messagingSenderId: '773797736663',
    projectId: 'report-alert-36a8b',
    authDomain: 'report-alert-36a8b.firebaseapp.com',
    storageBucket: 'report-alert-36a8b.appspot.com',
    measurementId: 'G-Z68JKS2S6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOOWYPBMG0TMjGiIJsNB65pTRshbdFS8Y',
    appId: '1:773797736663:android:1a5300a65bebdfb65f8092',
    messagingSenderId: '773797736663',
    projectId: 'report-alert-36a8b',
    storageBucket: 'report-alert-36a8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK7D8zIg1q8N-RRf_cYAajUZ9KaxRj4r4',
    appId: '1:773797736663:ios:c41d9546a6aacf595f8092',
    messagingSenderId: '773797736663',
    projectId: 'report-alert-36a8b',
    storageBucket: 'report-alert-36a8b.appspot.com',
    iosBundleId: 'com.ks.reportAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK7D8zIg1q8N-RRf_cYAajUZ9KaxRj4r4',
    appId: '1:773797736663:ios:c41d9546a6aacf595f8092',
    messagingSenderId: '773797736663',
    projectId: 'report-alert-36a8b',
    storageBucket: 'report-alert-36a8b.appspot.com',
    iosBundleId: 'com.ks.reportAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDoCJ15Rw7B4rV47oOPTJV_ipmCQz9r7o',
    appId: '1:773797736663:web:c013c2431f5ff3c85f8092',
    messagingSenderId: '773797736663',
    projectId: 'report-alert-36a8b',
    authDomain: 'report-alert-36a8b.firebaseapp.com',
    storageBucket: 'report-alert-36a8b.appspot.com',
    measurementId: 'G-GTZYF5F7ER',
  );
}
